# Generated by Django 6.1 on 2026-08-07 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_type', models.CharField(choices=[('account', '开通服务器账号'), ('permission', '申请权限'), ('other', '其他')], default='account', max_length=20, verbose_name='申请类型')),
                ('title', models.CharField(max_length=100, verbose_name='申请标题')),
                ('description', models.TextField(blank=True, verbose_name='申请内容')),
                ('target_server', models.CharField(blank=True, max_length=100, verbose_name='目标服务器')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='状态')),
                ('review_comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
            ],
            options={
                'verbose_name': '申请单',
                'verbose_name_plural': '申请单',
                'ordering': ['-created_at'],
            },
        ),
    ]
