# Generated by Django 6.1 on 2026-08-07 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('servers', '0002_remove_server_admin_key_remove_server_admin_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant_name',
            field=models.CharField(default='', max_length=50, verbose_name='申请人姓名'),
        ),
        migrations.AddField(
            model_name='application',
            name='contact',
            field=models.CharField(default='', help_text='手机号或邮箱，便于管理员联系', max_length=100, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人账号'),
        ),
        migrations.AlterField(
            model_name='application',
            name='target_server',
            field=models.ForeignKey(blank=True, help_text='从服务器列表中选择', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='servers.server', verbose_name='目标服务器'),
        ),
    ]
