# Generated by Django 6.1 on 2026-08-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_applicant_name_application_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='contact',
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default='', max_length=100, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='application',
            name='employee_id',
            field=models.CharField(default='', max_length=50, verbose_name='工号'),
        ),
        migrations.AddField(
            model_name='application',
            name='username',
            field=models.CharField(default='', max_length=50, verbose_name='用户名'),
        ),
    ]
