# Generated by Django 6.1 on 2026-08-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_application_contact_application_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='provision_note',
            field=models.TextField(blank=True, verbose_name='开通结果'),
        ),
        migrations.AddField(
            model_name='application',
            name='provisioned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='账号开通时间'),
        ),
    ]
