# Generated by Django 6.1 on 2026-08-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_provision_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='到期后账号自动停用，可不填', null=True, verbose_name='使用截止时间'),
        ),
    ]
