# Generated by Django 6.1 on 2026-08-07 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_valid_until'),
        ('servers', '0004_manageduser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='needs_sudo',
            field=models.BooleanField(default=False, help_text='该权限当天有效，次日自动失效', verbose_name='申请 root/sudo 权限'),
        ),
        migrations.CreateModel(
            name='SudoGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='机器用户名')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='授予时间')),
                ('expires_at', models.DateTimeField(help_text='当日 23:59:59 失效', verbose_name='失效时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='实际失效时间')),
                ('status', models.CharField(choices=[('active', '生效中'), ('expired', '已失效')], default='active', max_length=20, verbose_name='状态')),
                ('revoke_note', models.TextField(blank=True, verbose_name='失效说明')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sudo_grants', to='applications.application', verbose_name='关联申请')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_sudo', to=settings.AUTH_USER_MODEL, verbose_name='授予人（审批人）')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sudo_grants', to='servers.server', verbose_name='目标服务器')),
            ],
            options={
                'verbose_name': 'sudo 权限授予记录',
                'verbose_name_plural': 'sudo 权限授予记录',
                'ordering': ['-granted_at'],
            },
        ),
    ]
