# Generated by Django 6.1 on 2026-08-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_needs_sudo_sudogrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='migrate_from_dir',
            field=models.CharField(blank=True, help_text='可选，例如 /home/old/username：开通账号时自动迁移该目录到 /home/username', max_length=500, verbose_name='迁移来源目录'),
        ),
    ]
