# Generated by Django 6.1 on 2026-08-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_application_migrate_from_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='sudo_note',
            field=models.TextField(blank=True, verbose_name='sudo 授予结果'),
        ),
    ]
