# Generated by Django 6.1 on 2026-08-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_application_sudo_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applied_groups',
            field=models.CharField(blank=True, default='', help_text='用户申请时勾选的可附加分组，逗号分隔', max_length=500, verbose_name='附加分组'),
        ),
    ]
