# Generated by Django 6.1 on 2026-08-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_application_applied_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='apply_type',
            field=models.CharField(choices=[('create', '申请服务器账号'), ('transfer', '转移已有账号为受管用户')], default='create', max_length=20, verbose_name='申请类型'),
        ),
    ]
