# Generated by Django 6.1 on 2026-08-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_alter_application_apply_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='申请标题'),
        ),
    ]
