# Generated by Django 6.1 on 2026-08-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_alter_application_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='migrate_from_dir',
        ),
    ]
