# Generated by Django 6.1 on 2026-08-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_remove_application_migrate_from_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回'), ('withdrawn', '已撤回')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
