# Generated by Django 6.1 on 2026-08-11 06:37

import servers.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='initial_password',
            field=servers.fields.EncryptedTextField(blank=True, verbose_name='初始密码'),
        ),
    ]
