# Generated by Django 6.1 on 2026-08-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_application_initial_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='user_groups',
            field=models.CharField(blank=True, default='', help_text='可申请加入的用户组：sudo、docker、HwHiAiUser（逗号分隔）', max_length=100, verbose_name='申请用户组'),
        ),
        migrations.AlterField(
            model_name='application',
            name='apply_type',
            field=models.CharField(choices=[('create', '申请服务器账号'), ('transfer', '转移已有账号为受管用户'), ('admin', '申请平台管理员')], default='create', max_length=20, verbose_name='申请类型'),
        ),
    ]
