# Generated by Django 6.1 on 2026-08-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_application_user_groups_alter_application_apply_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='apply_type',
            field=models.CharField(choices=[('create', '申请服务器账号'), ('transfer', '转移已有账号为受管用户'), ('group', '申请用户组'), ('admin', '申请平台管理员')], default='create', max_length=20, verbose_name='申请类型'),
        ),
    ]
