# Generated by Django 6.1 on 2026-08-12 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_alter_application_apply_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='needs_sudo',
        ),
        migrations.RemoveField(
            model_name='application',
            name='sudo_note',
        ),
        migrations.RemoveField(
            model_name='application',
            name='valid_until',
        ),
        migrations.DeleteModel(
            name='SudoGrant',
        ),
    ]
