# Generated by Django 6.1 on 2026-08-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_remove_application_needs_sudo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='user_groups',
            field=models.CharField(blank=True, default='', help_text='可申请加入的用户组：sudo、docker（逗号分隔）', max_length=100, verbose_name='申请用户组'),
        ),
    ]
