# Generated by Django 6.1 on 2026-08-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0018_alter_application_user_groups"),
    ]
    operations = [
        migrations.AlterField(
            model_name="application",
            name="target_server",
            field=models.ForeignKey(
                help_text="请选择申请要操作的目标服务器",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="servers.server",
                verbose_name="目标服务器",
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                condition=models.Q(status="pending")
                | models.Q(status="approved", provisioned_at__isnull=True),
                fields=("target_server", "username"),
                name="uniq_active_server_username",
            ),
        ),
    ]
