# Generated by Django 6.1 on 2026-08-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_application_integrity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applied_groups',
        ),
    ]
