# Generated by Django 6.1 on 2026-08-07 16:17

import servers.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='用于识别的名称，如：生产环境 root', max_length=100, verbose_name='凭据名称')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', servers.fields.EncryptedTextField(blank=True, help_text='登录密码，存储时加密', verbose_name='密码')),
                ('private_key', servers.fields.EncryptedTextField(blank=True, help_text='SSH 私钥内容，存储时加密', verbose_name='私钥/密钥')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '管理凭据',
                'verbose_name_plural': '管理凭据',
                'ordering': ['name'],
            },
        ),
    ]
