# Generated by Django 6.1 on 2026-08-08 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitCodeBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitcode_id', models.PositiveBigIntegerField(help_text='GitCode 用户唯一 id，作为映射依据（login 可变，id 不变）', unique=True, verbose_name='GitCode 用户 id')),
                ('gitcode_username', models.CharField(blank=True, help_text='仅展示用', max_length=100, verbose_name='GitCode 用户名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='绑定时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gitcode_binding', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'GitCode 绑定',
                'verbose_name_plural': 'GitCode 绑定',
            },
        ),
    ]
