# Generated by Django 6.1 on 2026-08-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitcodebinding',
            name='gitcode_id',
            field=models.CharField(help_text='GitCode 用户唯一 id（24 位十六进制字符串，非数字），作为映射依据（login 可变，id 不变）', max_length=100, unique=True, verbose_name='GitCode 用户 id'),
        ),
    ]
