# Generated by Django 6.1 on 2026-08-08 14:44

import servers.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_gitcodebinding_gitcode_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitcode_client_id', models.CharField(blank=True, default='', max_length=200, verbose_name='GitCode Client ID')),
                ('gitcode_client_secret', servers.fields.EncryptedTextField(blank=True, help_text='存储时加密，页面不展示明文', verbose_name='GitCode Client Secret')),
                ('gitcode_scope', models.CharField(blank=True, default='all_user', max_length=200, verbose_name='GitCode Scope')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
    ]
