# Generated by Django 6.1 on 2026-08-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginLog',
        ),
    ]
