# Generated by Django 6.1 on 2026-08-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_gitcodebinding_to_socialaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfig',
            name='gitcode_scope',
        ),
    ]
