# Generated by Django 6.1 on 2026-08-09 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_systemconfig_gitcode_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfig',
            name='gitcode_client_id',
        ),
        migrations.RemoveField(
            model_name='systemconfig',
            name='gitcode_client_secret',
        ),
    ]
