# Generated by Django 6.1 on 2026-08-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='gitcode_enabled',
            field=models.BooleanField(default=True, verbose_name='启用 GitCode 登录'),
        ),
    ]
