# Generated by Django 6.1 on 2026-08-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_systemconfig_gitcode_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='site_base_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='站点地址'),
        ),
    ]
