# Generated by Django 6.1 on 2026-08-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_systemconfig_site_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='html_content',
            field=models.TextField(blank=True, help_text='编辑器生成的 HTML，用于 motd 高亮调色渲染', verbose_name='HTML 内容'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(blank=True, help_text='纯文本内容，写入服务器 motd 时使用', verbose_name='内容'),
        ),
    ]
