# Generated by Django 6.1 on 2026-08-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_announcement_html_content_alter_announcement_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='html_content',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='title',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(blank=True, help_text='markdown 子集：支持 # 标题、**加粗**、*斜体*、{red}颜色{/red}、[链接](url)', verbose_name='内容'),
        ),
    ]
