# Generated by Django 6.1 on 2026-08-17

from django.db import migrations, models


def invalidate_existing_codes(apps, schema_editor):
    """旧记录保存的是明文；升级时统一作废，用户可重新获取。"""
    EmailVerification = apps.get_model("accounts", "EmailVerification")
    EmailVerification.objects.filter(used=False).update(used=True)


class Migration(migrations.Migration):
    dependencies = [("accounts", "0015_remove_announcement_html_content_and_more")]

    operations = [
        migrations.AlterField(
            model_name="emailverification",
            name="code",
            field=models.CharField(max_length=128, verbose_name="验证码哈希"),
        ),
        migrations.RunPython(invalidate_existing_codes, migrations.RunPython.noop),
    ]
