# Generated by Django 6.1 on 2026-08-07 16:12

import servers.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='服务器名称')),
                ('host', models.CharField(help_text='IP 地址或域名', max_length=255, verbose_name='服务器地址')),
                ('port', models.PositiveIntegerField(default=22, verbose_name='端口')),
                ('admin_user', models.CharField(max_length=100, verbose_name='管理用户')),
                ('admin_key', servers.fields.EncryptedTextField(help_text='SSH 私钥等内容，存储时加密', verbose_name='管理用户密钥')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '服务器',
                'verbose_name_plural': '服务器',
                'ordering': ['name'],
            },
        ),
    ]
