# Generated by Django 6.1 on 2026-08-07 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='admin_key',
        ),
        migrations.RemoveField(
            model_name='server',
            name='admin_user',
        ),
        migrations.AddField(
            model_name='server',
            name='credential',
            field=models.ForeignKey(blank=True, help_text='选择已有的管理凭据（用户名/密码/密钥）', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servers', to='credentials.credential', verbose_name='管理凭据'),
        ),
    ]
