# Generated by Django 6.1 on 2026-08-07 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_remove_server_admin_key_remove_server_admin_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='组名')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='servers.server', verbose_name='所属服务器')),
            ],
            options={
                'verbose_name': '用户分组',
                'verbose_name_plural': '用户分组',
                'ordering': ['name'],
                'unique_together': {('server', 'name')},
            },
        ),
        migrations.AddField(
            model_name='server',
            name='default_group',
            field=models.ForeignKey(blank=True, help_text='用户申请账号时默认加入的分组', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='servers.usergroup', verbose_name='默认申请的用户分组'),
        ),
        migrations.AddField(
            model_name='server',
            name='extra_groups',
            field=models.ManyToManyField(blank=True, help_text='用户申请时可附加选择加入的分组', related_name='+', to='servers.usergroup', verbose_name='可附加申请的用户分组'),
        ),
    ]
