# Generated by Django 6.1 on 2026-08-07 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_usergroup_server_default_group_server_extra_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='最近同步时间')),
                ('groups', models.CharField(blank=True, max_length=500, verbose_name='机器分组')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_users', to='servers.server', verbose_name='所属服务器')),
            ],
            options={
                'verbose_name': '受管用户',
                'verbose_name_plural': '受管用户',
                'ordering': ['username'],
                'unique_together': {('server', 'username')},
            },
        ),
    ]
