# Generated by Django 6.1 on 2026-08-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_manageduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='nofile_limit',
            field=models.PositiveIntegerField(default=2048, help_text='该服务器上每个用户的最大打开文件数，0 表示不限制', verbose_name='文件数限制 nofile'),
        ),
        migrations.AddField(
            model_name='server',
            name='nproc_limit',
            field=models.PositiveIntegerField(default=128, help_text='该服务器上每个用户的最大进程数，0 表示不限制', verbose_name='进程数限制 nproc'),
        ),
    ]
