# Generated by Django 6.1 on 2026-08-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_server_nofile_limit_server_nproc_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='extra_groups',
        ),
        migrations.AlterField(
            model_name='server',
            name='default_group',
            field=models.CharField(blank=True, default='', help_text='用户申请账号时默认加入的分组，多个用英文逗号分隔', max_length=100, verbose_name='默认申请的用户分组'),
        ),
        migrations.AddField(
            model_name='server',
            name='extra_groups',
            field=models.CharField(blank=True, default='', help_text='用户申请时可附加选择加入的分组，多个用英文逗号分隔', max_length=500, verbose_name='可附加申请的用户分组'),
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
