# Generated by Django 6.1 on 2026-08-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_remove_server_extra_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='as_limit',
            field=models.PositiveIntegerField(default=0, help_text='每个用户最大虚拟内存（KB），0 表示不限制', verbose_name='虚拟内存限制 as(KB)'),
        ),
        migrations.AddField(
            model_name='server',
            name='core_limit',
            field=models.PositiveIntegerField(default=0, help_text='核心转储文件大小（KB），建议 0 防占磁盘，0 表示不限制', verbose_name='核心转储限制 core(KB)'),
        ),
        migrations.AddField(
            model_name='server',
            name='fsize_limit',
            field=models.PositiveIntegerField(default=0, help_text='每个用户最大单文件大小（KB），0 表示不限制', verbose_name='文件大小限制 fsize(KB)'),
        ),
        migrations.AddField(
            model_name='server',
            name='maxlogins_limit',
            field=models.PositiveIntegerField(default=0, help_text='每个用户最大同时登录会话数，0 表示不限制', verbose_name='最大登录数 maxlogins'),
        ),
        migrations.AlterField(
            model_name='server',
            name='nofile_limit',
            field=models.PositiveIntegerField(default=2048, help_text='每个用户最大打开文件数，0 表示不限制', verbose_name='文件数限制 nofile'),
        ),
        migrations.AlterField(
            model_name='server',
            name='nproc_limit',
            field=models.PositiveIntegerField(default=128, help_text='每个用户最大进程数，0 表示不限制', verbose_name='进程数限制 nproc'),
        ),
    ]
