# Generated by Django 6.1 on 2026-08-08 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0007_server_as_limit_server_core_limit_server_fsize_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerAdminBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_bindings', to=settings.AUTH_USER_MODEL, verbose_name='普通管理员')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_bindings', to='servers.server', verbose_name='服务器')),
            ],
            options={
                'verbose_name': '服务器管理员绑定',
                'verbose_name_plural': '服务器管理员绑定',
                'unique_together': {('server', 'admin')},
            },
        ),
    ]
