# Generated by Django 6.1 on 2026-08-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0008_serveradminbinding'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageduser',
            name='cpu_used',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='CPU 占用'),
        ),
        migrations.AddField(
            model_name='manageduser',
            name='disk_used',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='磁盘占用'),
        ),
        migrations.AddField(
            model_name='manageduser',
            name='mem_used',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='内存占用'),
        ),
        migrations.AddField(
            model_name='manageduser',
            name='usage_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='资源采集时间'),
        ),
    ]
