# Generated by Django 6.1 on 2026-08-09 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0009_manageduser_cpu_used_manageduser_disk_used_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manageduser',
            name='user',
            field=models.OneToOneField(blank=True, help_text='目标机器用户对应的 NRM 账号（一对一）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_user', to=settings.AUTH_USER_MODEL, verbose_name='绑定系统用户'),
        ),
    ]
