# Generated by Django 6.1 on 2026-08-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0010_manageduser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='init_script',
            field=models.CharField(blank=True, default='', help_text='服务器接入时在目标机远程下载并执行的脚本地址（如 NPU 配置脚本）', max_length=500, verbose_name='初始化脚本 URL'),
        ),
        migrations.AddField(
            model_name='server',
            name='is_npu',
            field=models.BooleanField(default=False, help_text='勾选后，用户申请的分组选择转换为 NPU 算力卡组选择', verbose_name='NPU 服务器'),
        ),
        migrations.AddField(
            model_name='server',
            name='npu_groups',
            field=models.CharField(blank=True, default='', help_text='检测 /dev/davinciN 后生成，如 npu,npu0,npu1（逗号分隔）', max_length=500, verbose_name='NPU 卡组（自动检测）'),
        ),
    ]
