# Generated by Django 6.1 on 2026-08-11 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0011_server_init_script_server_is_npu_server_npu_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagedUser',
        ),
    ]
