# Generated by Django 6.1 on 2026-08-11 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0012_delete_manageduser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineUserBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='机器用户名')),
                ('source', models.CharField(choices=[('transfer', '转移接管'), ('manual', '手动接管')], default='transfer', max_length=20, verbose_name='来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_user_bindings', to='servers.server', verbose_name='服务器')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_user_bindings', to=settings.AUTH_USER_MODEL, verbose_name='归属平台用户')),
            ],
            options={
                'verbose_name': '机器用户绑定',
                'verbose_name_plural': '机器用户绑定',
                'ordering': ['server', 'username'],
                'unique_together': {('server', 'username')},
            },
        ),
    ]
