# Generated by Django 6.1 on 2026-08-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0013_machineuserbinding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineuserbinding',
            name='source',
            field=models.CharField(choices=[('transfer', '转移接管'), ('manual', '手动接管'), ('create', '创建开通'), ('admin', '平台管理员'), ('group', '用户组')], default='transfer', max_length=20, verbose_name='来源'),
        ),
    ]
