# Generated by Django 6.1 on 2026-08-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0014_alter_machineuserbinding_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='init_script',
        ),
    ]
