# Generated by Django 6.1 on 2026-08-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0015_remove_server_init_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='device_info_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='最近一次成功采集的设备信息（CPU/内存/硬盘/NPU），查询失败时回退展示', verbose_name='设备信息快照'),
        ),
        migrations.AddField(
            model_name='server',
            name='device_info_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='设备信息更新时间'),
        ),
    ]
