# Generated by Django 6.1 on 2026-08-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0016_server_device_info_snapshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='as_limit',
        ),
        migrations.RemoveField(
            model_name='server',
            name='core_limit',
        ),
        migrations.RemoveField(
            model_name='server',
            name='fsize_limit',
        ),
        migrations.RemoveField(
            model_name='server',
            name='maxlogins_limit',
        ),
        migrations.RemoveField(
            model_name='server',
            name='nofile_limit',
        ),
        migrations.RemoveField(
            model_name='server',
            name='nproc_limit',
        ),
    ]
