# Generated by Django 6.1 on 2026-08-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servers", "0017_remove_server_as_limit_remove_server_core_limit_and_more"),
    ]
    operations = [
        migrations.AddField(
            model_name="server",
            name="ssh_host_key_fingerprint",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "OpenSSH SHA256 指纹。首次请选“保存并测试连接”获取候选指纹，"
                    "通过可信渠道核对后填入；指纹变化时系统将拒绝连接。"
                ),
                max_length=80,
                verbose_name="SSH 主机指纹",
            ),
        ),
    ]
