# Generated by Django 6.1 on 2026-08-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0018_server_ssh_host_key_fingerprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="server",
            name="extra_groups",
        ),
        migrations.RemoveField(
            model_name='server',
            name='is_npu',
        ),
        migrations.RemoveField(
            model_name='server',
            name='npu_groups',
        ),
        migrations.AlterField(
            model_name='server',
            name='device_info_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='最近一次成功采集的设备信息（CPU/内存/硬盘），查询失败时回退展示', verbose_name='设备信息快照'),
        ),
    ]
