# Generated by Django 6.1 on 2026-08-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0019_remove_server_is_npu_remove_server_npu_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='device_info_updated_at',
        ),
    ]
