"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 生产环境务必通过环境变量 NRM_SECRET_KEY 提供。
# 注意：SECRET_KEY 也是凭据等敏感字段的 Fernet 加密密钥来源，
# 变更后历史密文将无法解密（需数据迁移），开发默认值保持不变。
SECRET_KEY = os.environ.get(
    "NRM_SECRET_KEY",
    "django-insecure-er9k0na5u*y-71#f$a3=nd*1+2od&-3b1-sb@x$xce5mq3y22f",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["192.168.9.216"]

# Django 6.1 启用 Origin 校验：经非默认端口（18888）访问时，
# 请求头 Origin 必须匹配 CSRF_TRUSTED_ORIGINS，否则 403
# "Origin checking failed - http://192.168.9.216:18888 does not match any trusted origins"
CSRF_TRUSTED_ORIGINS = ["http://192.168.9.216:18888"]

# GitCode OAuth 回调基准地址：固定回调 URL，避免随请求 host 漂移
# 导致 GitCode 应用配置的回调地址与实际生成的 redirect_uri 不一致（回调不匹配）。
# 修改域名/端口时需同步更新此处与 GitCode 应用管理页的回调配置。
GITCODE_CALLBACK_BASE_URL = "http://192.168.9.216:18888"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "crispy_forms",
    "crispy_bootstrap3",
    "django_select2",
    "widget_tweaks",
    "axes",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "accounts.providers.gitcode",
    "accounts",
    "applications",
    "servers",
    "credentials",
    "notifications",
]

SITE_ID = 1

# 缓存：django-select2 的 Heavy widget 需要缓存后端（存查询状态）
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    }
}

# 表单渲染：crispy-forms（Bootstrap 3 模板包）
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap3"
CRISPY_TEMPLATE_PACK = "bootstrap3"

# 登录防爆破（django-axes）：15 分钟内同用户名+IP 失败 5 次锁定
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 0.25  # 单位：小时；0.25 = 15 分钟
AXES_LOCKOUT_PARAMETERS = ["username", "ip_address"]
AXES_RESET_ON_SUCCESS = True

AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# django-allauth：仅启用第三方 OAuth 登录能力（账号注册/密码等沿用自研机制）
ACCOUNT_LOGIN_METHODS = {"username"}
ACCOUNT_SIGNUP_FIELDS = []  # 注册走自研表单，不用 allauth 注册页
ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_QUERY_EMAIL = False
SOCIALACCOUNT_LOGIN_ON_GET = False
# 首次 GitCode 登录走 signup 确认页（注册新账号/绑定已有账号），已绑定用户直接登录
SOCIALACCOUNT_ADAPTER = "accounts.adapter.GitCodeSocialAccountAdapter"

# GitCode OAuth 配置由 django-allauth 的 SocialApp 管理（系统设置页维护）

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "axes.middleware.AxesMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# 认证跳转
LOGIN_URL = "accounts:login"
# 登录后跳转"我的申请"（普通用户可访问）；原指向 applications:list（仅管理员），
# 普通用户登录后会被 staff_required 弹回登录页形成循环
LOGIN_REDIRECT_URL = "applications:my"
LOGOUT_REDIRECT_URL = "accounts:login"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"

# 项目自研静态资源（app.css / app.js）放在根目录 static/ 下，
# 不属于任何 app，需显式登记到 STATICFILES_DIRS，
# 这样 DEBUG=True 时 staticfiles 应用才能找到并直接 serve。
STATICFILES_DIRS = [BASE_DIR / "static"]
