"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------------
# 运行模式与配置文件加载
#   NRM_ENV=prod  -> 部署模式（严格按 .env.prod 执行）
#   其他（含未设置 / dev）-> 开发模式（宽松 + 详细日志）
# 配置文件经 python-dotenv 加载；override=False：若运行环境已注入同名环境变量
# （systemd/容器/CI），不会被 .env 文件覆盖，安全。未安装 python-dotenv 时
# 退回纯环境变量模式。
# ---------------------------------------------------------------------------
NRM_ENV = os.environ.get("NRM_ENV", "dev").strip().lower()
MODE = "deploy" if NRM_ENV == "prod" else "dev"


def _env_bool(name: str, default: bool = False) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


try:
    from dotenv import load_dotenv

    _env_file = ".env.prod" if MODE == "deploy" else ".env"
    if Path(_env_file).is_file():
        load_dotenv(_env_file, override=False)
except ImportError:
    pass

# 测试环境标记：servers 等 app 的 ready() 据此跳过启动期后台任务（如 NPU 状态同步）。
# conftest.py 在测试进程设置环境变量 DJANGO_TESTING=1；此处转为 Django 设置供 app 读取
# （此前仅设了环境变量、未定义对应设置，导致跳过逻辑从未生效）。
DJANGO_TESTING = os.environ.get("DJANGO_TESTING", "") == "1"

# NPU 状态启动同步：仅部署模式默认开启（预热内存缓存，避免申请页首次访问 SSH 卡顿）；
# 开发模式默认关闭——启动即对全部 NPU 服务器 SSH 探测会干扰本地调测，
# 开发态首次访问时由 get_npu_state_cached 懒加载，效果一致。
# 如需在开发模式也启动同步：设置 NRM_SYNC_NPU=1。
NPU_SYNC_ON_STARTUP = MODE == "deploy" or os.environ.get("NRM_SYNC_NPU", "").strip().lower() == "1"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 生产环境务必通过环境变量 NRM_SECRET_KEY 提供。
# 注意：SECRET_KEY 也是凭据等敏感字段的 Fernet 加密密钥来源，
# 变更后历史密文将无法解密（需数据迁移），开发默认值保持不变。
_SECRET_KEY = os.environ.get("NRM_SECRET_KEY")
if MODE == "deploy" and not _SECRET_KEY:
    # 部署模式严禁使用默认开发密钥
    raise RuntimeError(
        "部署模式(DEPLOY)要求通过环境变量 NRM_SECRET_KEY 提供密钥，禁止使用 settings.py 中的默认开发密钥。"
    )
SECRET_KEY = _SECRET_KEY or "django-insecure-er9k0na5u*y-71#f$a3=nd*1+2od&-3b1-sb@x$xce5mq3y22f"

# ---------------------------------------------------------------------------
# 运行模式行为
#   开发模式(dev)  : DEBUG=True、ALLOWED_HOSTS=*（放行域名拦截）、
#                    CSRF 来源宽松、日志详细（含 SQL/请求/SSH）
#   部署模式(prod) : DEBUG 取 NRM_DEBUG、ALLOWED_HOSTS/CSRF 严格取自配置文件，
#                    缺失即报错，不裸奔
# ---------------------------------------------------------------------------
if MODE == "dev":
    DEBUG = True
    # 开发模式：任意 host 均可访问，不做域名拦截
    ALLOWED_HOSTS = ["*"]
    # CSRF 来源：通配符 + 环境变量显式来源。
    # 注意：Django 6.1 对裸 "http://*" 通配匹配有限（实测不匹配具体 Origin），
    # 反代/生产入口必须显式加入实际来源（如 http://192.168.9.216:18888），
    # 因此在 dev 模式同样读取 .env 的 NRM_CSRF_TRUSTED_ORIGINS 并追加。
    _csrf_env = [o.strip() for o in os.environ.get("NRM_CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()]
    CSRF_TRUSTED_ORIGINS = ["http://*", "https://*"] + _csrf_env
    LOG_LEVEL = "DEBUG"
else:  # deploy
    DEBUG = os.environ.get("NRM_DEBUG", "False").strip().lower() == "true"
    # 部署模式：ALLOWED_HOSTS 必须来自配置文件，缺失即报错
    _allowed_hosts_raw = os.environ.get("NRM_ALLOWED_HOSTS", "")
    if not _allowed_hosts_raw.strip():
        raise RuntimeError(
            "部署模式(DEPLOY)要求配置文件提供 NRM_ALLOWED_HOSTS，"
            "请在 .env.prod 中设置，例如 NRM_ALLOWED_HOSTS=example.com,www.example.com"
        )
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_raw.split(",") if h.strip()]
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get("NRM_CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()]
    LOG_LEVEL = os.environ.get("NRM_LOG_LEVEL", "INFO").strip().upper()

# 生产环境默认启用 Django 官方部署安全基线。
SECURE_SSL_REDIRECT = MODE == "deploy" and _env_bool("NRM_SECURE_SSL_REDIRECT", True)
SESSION_COOKIE_SECURE = MODE == "deploy"
CSRF_COOKIE_SECURE = MODE == "deploy"
SECURE_HSTS_SECONDS = int(os.environ.get("NRM_SECURE_HSTS_SECONDS", "31536000")) if MODE == "deploy" else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = MODE == "deploy" and _env_bool("NRM_SECURE_HSTS_INCLUDE_SUBDOMAINS")
SECURE_HSTS_PRELOAD = MODE == "deploy" and _env_bool("NRM_SECURE_HSTS_PRELOAD")
SECURE_CONTENT_TYPE_NOSNIFF = True
if MODE == "deploy" and _env_bool("NRM_TRUST_X_FORWARDED_PROTO"):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# GitCode OAuth 回调基准地址：一律从环境变量（.env / .env.prod）读取，禁止硬编码。
# 未配置时为空串，站点地址由数据库 SystemConfig.site_base_url 兜底。
GITCODE_CALLBACK_BASE_URL = os.environ.get("NRM_GITCODE_CALLBACK_BASE_URL", "").strip()

# ---------------------------------------------------------------------------
# 日志
#   开发模式: 各级 DEBUG，打印 SQL(django.db.backends)、请求、SSH(paramiko) 等
#   部署模式: 级别由 NRM_LOG_LEVEL 控制（默认 INFO）；
#            配置文件提供 NRM_LOG_FILE 则追加滚动文件日志
# ---------------------------------------------------------------------------
_LOG_HANDLERS = ["console"]
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname:<8} {name} {module}:{lineno} | {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname:<8} {name} | {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose" if MODE == "dev" else "simple",
            "level": LOG_LEVEL,
        },
    },
    "root": {
        "handlers": _LOG_HANDLERS,
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {"handlers": _LOG_HANDLERS, "level": LOG_LEVEL, "propagate": False},
        "django.db.backends": {
            "handlers": _LOG_HANDLERS,
            "level": "DEBUG" if MODE == "dev" else LOG_LEVEL,
            "propagate": False,
        },
        "django.request": {"handlers": _LOG_HANDLERS, "level": LOG_LEVEL, "propagate": False},
        "axes": {"handlers": _LOG_HANDLERS, "level": LOG_LEVEL, "propagate": False},
        "allauth": {"handlers": _LOG_HANDLERS, "level": LOG_LEVEL, "propagate": False},
        "paramiko": {"handlers": _LOG_HANDLERS, "level": LOG_LEVEL, "propagate": False},
        "servers": {"handlers": _LOG_HANDLERS, "level": LOG_LEVEL, "propagate": False},
        "applications": {"handlers": _LOG_HANDLERS, "level": LOG_LEVEL, "propagate": False},
        "accounts": {"handlers": _LOG_HANDLERS, "level": LOG_LEVEL, "propagate": False},
        "credentials": {"handlers": _LOG_HANDLERS, "level": LOG_LEVEL, "propagate": False},
        "notifications": {"handlers": _LOG_HANDLERS, "level": LOG_LEVEL, "propagate": False},
    },
}
# 部署模式可选：配置文件提供 NRM_LOG_FILE 则追加滚动文件日志
if MODE != "dev":
    _log_file = os.environ.get("NRM_LOG_FILE")
    if _log_file:
        LOGGING["handlers"]["file"] = {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": _log_file,
            "maxBytes": 10 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "verbose",
            "level": LOG_LEVEL,
        }
        for _lg in LOGGING["loggers"].values():
            _lg["handlers"] = ["console", "file"]
        LOGGING["root"]["handlers"] = ["console", "file"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "crispy_forms",
    "crispy_bootstrap3",
    "django_select2",
    "widget_tweaks",
    "axes",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "accounts.providers.gitcode",
    "accounts",
    "applications",
    "servers",
    "credentials",
    "notifications",
]

SITE_ID = 1

# 缓存：django-select2 的 Heavy widget 需要缓存后端（存查询状态）
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    }
}

# 表单渲染：crispy-forms（Bootstrap 3 模板包）
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap3"
CRISPY_TEMPLATE_PACK = "bootstrap3"

# 登录防爆破（django-axes）：15 分钟内同用户名+IP 失败 5 次锁定
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 0.25  # 单位：小时；0.25 = 15 分钟
AXES_LOCKOUT_PARAMETERS = ["username", "ip_address"]
AXES_RESET_ON_SUCCESS = True

AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# django-allauth：仅启用第三方 OAuth 登录能力（账号注册/密码等沿用自研机制）
ACCOUNT_LOGIN_METHODS = {"username"}
ACCOUNT_SIGNUP_FIELDS = []  # 注册走自研表单，不用 allauth 注册页
ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_QUERY_EMAIL = False
SOCIALACCOUNT_LOGIN_ON_GET = False
# 首次 GitCode 登录走 signup 确认页（注册新账号/绑定已有账号），已绑定用户直接登录
SOCIALACCOUNT_ADAPTER = "accounts.adapter.GitCodeSocialAccountAdapter"

# GitCode OAuth 配置由 django-allauth 的 SocialApp 管理（系统设置页维护）

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "axes.middleware.AxesMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# 认证跳转
LOGIN_URL = "accounts:login"
# 登录后跳转"我的申请"（普通用户可访问）；原指向 applications:list（仅管理员），
# 普通用户登录后会被 staff_required 弹回登录页形成循环
LOGIN_REDIRECT_URL = "applications:my"
LOGOUT_REDIRECT_URL = "accounts:login"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# 项目自研静态资源（app.css / app.js）放在根目录 static/ 下，
# 不属于任何 app，需显式登记到 STATICFILES_DIRS，
# 这样 DEBUG=True 时 staticfiles 应用才能找到并直接 serve。
STATICFILES_DIRS = [BASE_DIR / "static"]
