# Generated by Django 6.1 on 2026-08-07 16:55

import servers.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, verbose_name='SMTP 服务器')),
                ('port', models.PositiveIntegerField(default=465, verbose_name='端口')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('password', servers.fields.EncryptedTextField(blank=True, help_text='存储时加密', verbose_name='密码/授权码')),
                ('from_email', models.CharField(blank=True, help_text='留空则使用用户名', max_length=255, verbose_name='发件人地址')),
                ('use_tls', models.BooleanField(default=True, verbose_name='使用 SSL/TLS')),
                ('enabled', models.BooleanField(default=False, verbose_name='启用邮件通知')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '邮件配置',
                'verbose_name_plural': '邮件配置',
            },
        ),
    ]
