# Generated by Django 6.1 on 2026-08-07 16:57

import servers.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('url', models.URLField(help_text='收到事件时推送 JSON 的地址', verbose_name='Webhook URL')),
                ('secret', servers.fields.EncryptedTextField(blank=True, help_text='可选，用于鉴权（存储时加密）', verbose_name='密钥')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Webhook 配置',
                'verbose_name_plural': 'Webhook 配置',
            },
        ),
    ]
