# Generated by Django 6.1 on 2026-08-08 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_webhookconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookconfig',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='留空为全局 Webhook', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to=settings.AUTH_USER_MODEL, verbose_name='所属管理员'),
        ),
    ]
