# Generated by Django 6.1 on 2026-08-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_webhookconfig_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailconfig',
            name='use_tls',
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='use_ssl',
            field=models.BooleanField(default=True, help_text='465 端口为 SSL 直连；587/25 端口请取消勾选（STARTTLS）', verbose_name='使用 SSL 直连'),
        ),
    ]
