# Generated by Django 6.1 on 2026-08-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_emailconfig_use_tls_emailconfig_use_ssl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookconfig',
            name='name',
            field=models.CharField(choices=[('feishu', '飞书'), ('generic', '通用（原始 JSON）')], default='feishu', max_length=100, verbose_name='平台'),
        ),
    ]
