# Generated by Django 6.1 on 2026-08-12 03:24

import servers.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_webhookconfig_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='mail_webhook_token',
            field=servers.fields.EncryptedTextField(blank=True, help_text='请求头 X-Webhook-Token', verbose_name='邮件 Webhook Token'),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='mail_webhook_url',
            field=servers.fields.EncryptedTextField(blank=True, help_text='如 http://host/webhook/mail', verbose_name='邮件 Webhook URL'),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='send_via',
            field=models.CharField(choices=[('smtp', 'SMTP 直连'), ('webhook', '邮件 Webhook')], default='smtp', max_length=10, verbose_name='发送方式'),
        ),
    ]
